version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "jquery",
    "mocha",
    "browser",
    "jest",
    "jasmine",
    "mongo",
    "vitest",
    "cypress"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "ruff"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"