# CI/CD Pipeline for laundr.me

name: Laundr.me CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint & Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend linting dependencies
        run: pip install flake8 black isort

      - name: Run backend linters
        run: |
          flake8 backend/
          black --check backend/
          isort --check-only backend/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install frontend linting dependencies
        run: npm --prefix frontend install

      - name: Run frontend linter (e.g., ESLint)
        run: echo "Frontend linter step to be configured" # Placeholder

  type-check:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install mypy
        run: pip install mypy types-requests

      - name: Run mypy
        run: mypy backend/

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt && pip install -r backend/requirements-dev.txt

      - name: Run backend tests
        run: pytest backend/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: npm --prefix frontend install

      - name: Run frontend tests
        run: echo "Frontend test step to be configured" # Placeholder

  spec-invariants:
    name: Spec Invariant Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run spec invariant checks
        run: echo "Spec invariant check step to be configured" # Placeholder
